application: polymer-test
version: default
runtime: python27
threadsafe: yes
api_version: 1

handlers:

 - url: /
   static_files: index.html
   upload: index.html

 - url: /precache.json
   static_files: precache.json
   upload: precache.json

 - url: /api/.*
   script: main.app
   secure: always

 - url: /bower_components/
   static_dir: ../bower_components

 - url: /elements/
   static_dir: elements

 - url: /images/
   static_dir: images

 - url: /scripts/
   static_dir: scripts

 - url: /styles/
   static_dir: styles

 - url: /.*
   static_files: 404.html
   upload: 404.html

libraries:
- name: webapp2
  version: latest

- name: PIL
  version: "1.1.7"

- name: jinja2
  version: "2.6"

- name: pycrypto
  version: "2.6"

- name: ssl
  version: latest

builtins:
- deferred: on

- appstats: on

inbound_services:
- warmup
